# Generated by Django 4.0.3 on 2024-02-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoes',
            name='picture',
            field=models.URLField(null=True),
        ),
    ]
